In [1]:
# -*- coding: utf-8 -*-
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import json
import csv

df = pd.read_json('initial/underground.json', typ='frame')

In [2]:
df

,BPAAmount,FullFeaturedBPAAmount,ID,Latitude_WGS84,Line,LittleFunctionalBPAAmount,Longitude_WGS84,ModeOnEvenDays,ModeOnOddDays,Name,NameOfStation,RepairOfEscalators,geoData,global_id
0,4.0,NaN,326,55.756767,��������-������� �����,4.0,37.630985,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"�����-�����, ����-����� 3 � �������� ���������",�����-�����,[],"{'type': 'Point', 'coordinates': [37.6309849, ...",1773538
1,4.0,NaN,331,55.757315,��������-������� �����,4.0,37.631677,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"�����-�����, ����-����� 8 � �������� ���������",�����-�����,[],"{'type': 'Point', 'coordinates': [37.6316766, ...",1773539
2,4.0,NaN,327,55.756882,��������-������� �����,4.0,37.631270,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"�����-�����, ����-����� 4 � �������� ���������",�����-�����,[],"{'type': 'Point', 'coordinates': [37.6312698, ...",1773540
3,4.0,NaN,330,55.757236,��������-������� �����,4.0,37.631951,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"�����-�����, ����-����� 7 � �������� ���������",�����-�����,[],"{'type': 'Point', 'coordinates': [37.6319506, ...",1773541
4,4.0,NaN,322,55.753198,��������-������� �����,4.0,37.633105,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"�����-�����, ����-����� 6 � ����� ���������",�����-�����,[],"{'type': 'Point', 'coordinates': [37.6331045, ...",1773542
5,4.0,NaN,321,55.753112,��������-������� �����,4.0,37.633641,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"�����-�����, ����-����� 5 � ����� ���������",�����-�����,[],"{'type': 'Point', 'coordinates': [37.6336406, ...",1773543
6,NaN,NaN,317,55.754134,��������-������� �����,NaN,37.634177,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"�����-�����, ����-����� 1 �� ������ ���������",�����-�����,[],"{'type': 'Point', 'coordinates': [37.6341765, ...",1773544
7,4.0,NaN,318,55.754024,��������-������� �����,4.0,37.634973,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"�����-�����, ����-����� 2 � ����� ���������",�����-�����,[],"{'type': 'Point', 'coordinates': [37.6349733, ...",1773545
8,4.0,NaN,325,55.756604,��������-������� �����,4.0,37.629649,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:35:00; �������� � 01:00:00; ����...,"�����-�����, ����-����� 2 � �������� ���������",�����-�����,[],"{'type': 'Point', 'coordinates': [37.6296491, ...",1773546
9,4.0,NaN,280,55.655386,��������-������� �����,4.0,37.539238,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"���������, ����-����� 6 � ����� ���������",���������,[],"{'type': 'Point', 'coordinates': [37.5392381, ...",1773547
10,2.0,NaN,447,55.660114,���������-����������� �����,2.0,37.752643,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"�������������, ����-����� 2 � �������� ���������",�������������,[],"{'type': 'Point', 'coordinates': [37.7526435, ...",1773548
11,2.0,NaN,446,55.660051,���������-����������� �����,2.0,37.751743,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"�������������, ����-����� 1 � �������� ���������",�������������,[],"{'type': 'Point', 'coordinates': [37.7517426, ...",1773549
12,2.0,NaN,91,55.545011,��������� ����� ˸����� �����,2.0,37.541645,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"������� �������� �������, ����-����� � ���������",������� �������� �������,[],"{'type': 'Point', 'coordinates': [37.5416454, ...",1773550
13,6.0,NaN,502,55.570255,�����������-������������� �����,6.0,37.576439,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"������� ������� ��������, ����-����� 4 � �����...",������� ������� ��������,[],"{'type': 'Point', 'coordinates': [37.5764394, ...",1773551
14,6.0,NaN,501,55.570093,�����������-������������� �����,6.0,37.577148,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"������� ������� ��������, ����-����� 3 � �����...",������� ������� ��������,[],"{'type': 'Point', 'coordinates': [37.5771475, ...",1773552
15,3.0,NaN,89,55.537681,��������� ����� ˸����� �����,3.0,37.514940,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"��������� �����, ����-����� � ���������",��������� �����,[],"{'type': 'Point', 'coordinates': [37.5149399, ...",1773553
16,3.0,NaN,383,55.653075,��������� �����,3.0,37.617920,�������� � 05:25:00; �������� � 01:00:00; ����...,�������� � 05:25:00; �������� � 01:00:00; ����...,"����������, ����-����� 2 � ����� ���������",����������,[],"{'type': 'Point', 'coordinates': [37.61792, 55...",1773554
17,4.0,NaN,384,55.653213,��������� �����,4.0,37.620790,�������� � 05:25:00; �������� � 01:00:00; ����...,�������� � 05:25:00; �������� � 01:00:00; ����...,"����������, ����-����� 1 � �������� ���������",����������,[{'RepairOfEscalators': '27.04.2018-31.05.2018'}],"{'type': 'Point', 'coordinates': [37.6207903, ...",1773555
18,4.0,NaN,277,55.656323,��������-������� �����,4.0,37.540220,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"���������, ����-����� 3 � ����� ���������",���������,[],"{'type': 'Point', 'coordinates': [37.5402196, ...",1773556
19,3.0,NaN,281,55.658154,��������-������� �����,3.0,37.540987,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"���������, ����-����� 1 � �������� ���������",���������,[],"{'type': 'Point', 'coordinates': [37.5409869, ...",1773557
20,3.0,NaN,151,55.634665,�������������� �����,3.0,37.657145,�������� � 05:35:00; �������� � 01:00:00; ����...,�������� � 05:35:00; �������� � 01:00:00; ����...,"��������������, ����-����� 1 � ����� ���������",��������������,[],"{'type': 'Point', 'coordinates': [37.6571455, ...",1773558
21,3.0,NaN,152,55.635053,�������������� �����,3.0,37.657696,�������� � 05:35:00; �������� � 01:00:00; ����...,�������� � 05:35:00; �������� � 01:00:00; ����...,"��������������, ����-����� 2 � ����� ���������",��������������,[],"{'type': 'Point', 'coordinates': [37.6576959, ...",1773559
22,3.0,NaN,149,55.636721,�������������� �����,3.0,37.655357,�������� � 05:35:00; �������� � 01:00:00; ����...,�������� � 05:35:00; �������� � 01:00:00; ����...,"��������������, ����-����� 2 � �������� ���������",��������������,[],"{'type': 'Point', 'coordinates': [37.6553567, ...",1773560
23,5.0,NaN,377,55.652889,��������� �����,5.0,37.596467,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"���������, ����-����� 4 � ����� ���������",���������,[],"{'type': 'Point', 'coordinates': [37.5964667, ...",1773561
24,3.0,NaN,284,55.657859,��������-������� �����,3.0,37.541866,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"���������, ����-����� 4 � �������� ���������",���������,[],"{'type': 'Point', 'coordinates': [37.5418665, ...",1773562
25,3.0,NaN,150,55.636917,�������������� �����,3.0,37.656097,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"��������������, ����-����� 3 � �������� ���������",��������������,[],"{'type': 'Point', 'coordinates': [37.656097, 5...",1773563
26,2.0,NaN,448,55.659911,���������-����������� �����,2.0,37.752150,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"�������������, ����-����� 3 � �������� ���������",�������������,[],"{'type': 'Point', 'coordinates': [37.7521499, ...",1773564
27,4.0,NaN,791,55.773386,��������-����������������� �����,4.0,37.544590,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"�������, ����-����� 2 �� 2-� ���������",�������,[],"{'type': 'Point', 'coordinates': [37.54459, 55...",1773565
28,4.0,NaN,790,55.774000,��������-����������������� �����,4.0,37.544666,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"�������, ����-����� 1 �� 2-� ���������",�������,[],"{'type': 'Point', 'coordinates': [37.5446657, ...",1773566
29,2.0,NaN,792,55.773223,��������-����������������� �����,2.0,37.548884,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"�������, ����-����� 1 � 1-� ���������",�������,[],"{'type': 'Point', 'coordinates': [37.5488844, ...",1773567
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1009,8.0,8.0,1047,55.864590,���������-����������� �����,NaN,37.546029,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"�����������, ����-����� 5, ��������� 1",�����������,[],"{'type': 'Point', 'coordinates': [37.546029, 5...",859914677
1010,8.0,8.0,1048,55.864949,���������-����������� �����,NaN,37.545471,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"�����������, ����-����� 6, ��������� 1",�����������,[],"{'type': 'Point', 'coordinates': [37.545471, 5...",859914687
1011,8.0,8.0,1049,55.867540,���������-����������� �����,NaN,37.547928,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"�����������, ����-����� 7, ��������� 2",�����������,[],"{'type': 'Point', 'coordinates': [37.547928, 5...",859914698
1012,8.0,8.0,1050,55.867778,���������-����������� �����,NaN,37.547848,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"�����������, ����-����� 8, ��������� 2",�����������,[],"{'type': 'Point', 'coordinates': [37.547848, 5...",859914704
1013,8.0,8.0,1051,55.867250,���������-����������� �����,NaN,37.546311,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"�����������, ����-����� 9, ��������� 2",�����������,[],"{'type': 'Point', 'coordinates': [37.546311, 5...",859914715
1014,8.0,8.0,1052,55.867575,���������-����������� �����,NaN,37.546223,�������� � 05:30:00; �������� � 01:00:00; ����...,�������� � 05:30:00; �������� � 01:00:00; ����...,"�����������,����-����� 10, ��������� 2",�����������,[],"{'type': 'Point', 'coordinates': [37.546223, 5...",859914725
1015,6.0,6.0,1053,55.689594,����������� �����,NaN,37.483401,"�������� � 05:30:00, �������� � 01:00:00, ����...",�������� � 05:30:00; �������� � 01:00:00; ����...,"����������� ��������, ����-����� 1",����������� ��������,[],"{'type': 'Point', 'coordinates': [37.483401, 5...",886135230
1016,6.0,6.0,1054,55.688560,����������� �����,NaN,37.483989,"�������� � 05:30:00, �������� � 01:00:00, ����...",�������� � 05:30:00; �������� � 01:00:00; ����...,"����������� ��������, ����-����� 2",����������� ��������,[],"{'type': 'Point', 'coordinates': [37.483989, 5...",886135271
1017,6.0,6.0,1055,55.671377,����������� �����,NaN,37.450153,"�������� � 05:30:00, �������� � 01:00:00, ����...",�������� � 05:30:00; �������� � 01:00:00; ����...,"�������, ����-����� 2, ��������� 1",�������,[],"{'type': 'Point', 'coordinates': [37.450153, 5...",886135291
1018,6.0,6.0,1056,55.671623,����������� �����,NaN,37.450714,"�������� � 05:30:00, �������� � 01:00:00, ����...",�������� � 05:30:00; �������� � 01:00:00; ����...,"�������, ����-����� 3, ��������� 1",�������,[],"{'type': 'Point', 'coordinates': [37.450714, 5...",886135317
1019,6.0,6.0,1057,55.670665,����������� �����,NaN,37.451291,"�������� � 05:30:00, �������� � 01:00:00, ����...",�������� � 05:30:00; �������� � 01:00:00; ����...,"�������, ����-����� 4, ��������� 1",�������,[],"{'type': 'Point', 'coordinates': [37.451291, 5...",886135393
1020,6.0,6.0,1058,55.670413,����������� �����,NaN,37.447595,"�������� � 05:30:00, �������� � 01:00:00, ����...",�������� � 05:30:00; �������� � 01:00:00; ����...,"�������, ����-����� 1, ��������� 2",�������,[],"{'type': 'Point', 'coordinates': [37.447595, 5...",886135443
1021,4.0,4.0,1059,55.659399,����������� �����,NaN,37.418369,"�������� � 05:30:00, �������� � 01:00:00, ����...","�������� � 05:30:00, �������� � 01:00:00, ����...","��������, ����-����� 3, ��������� 1",��������,[],"{'type': 'Point', 'coordinates': [37.418369, 5...",886135457
1022,4.0,4.0,1060,55.659401,����������� �����,NaN,37.418985,"�������� � 05:30:00, �������� � 01:00:00, ����...","�������� � 05:30:00, �������� � 01:00:00, ����...","��������, ����-����� 4, ��������� 1",��������,[],"{'type': 'Point', 'coordinates': [37.418985, 5...",886135472
1023,4.0,4.0,1061,55.659374,����������� �����,NaN,37.415586,"�������� � 05:30:00, �������� � 01:00:00, ����...","�������� � 05:30:00, �������� � 01:00:00, ����...","��������, ����-����� 1, ��������� 2",��������,[],"{'type': 'Point', 'coordinates': [37.415586, 5...",886135482
1024,4.0,4.0,1062,55.659387,����������� �����,NaN,37.416347,"�������� � 05:30:00, �������� � 01:00:00, ����...","�������� � 05:30:00, �������� � 01:00:00, ����...","��������, ����-����� 2, ��������� 2",��������,[],"{'type': 'Point', 'coordinates': [37.416347, 5...",886135498
1025,4.0,4.0,1063,55.650061,����������� �����,NaN,37.391905,"�������� � 05:30:00, �������� � 01:00:00, ����...","�������� � 05:30:00, �������� � 01:00:00, ����...","��������, ����-����� 3, ��������� 1",��������,[],"{'type': 'Point', 'coordinates': [37.391905, 5...",886135518
1026,4.0,4.0,1064,55.648598,����������� �����,NaN,37.389874,"�������� � 05:30:00, �������� � 01:00:00, ����...","�������� � 05:30:00, �������� � 01:00:00, ����...","��������, ����-����� 1, ��������� 2",��������,[],"{'type': 'Point', 'coordinates': [37.389874, 5...",886135534
1027,4.0,4.0,1065,55.648455,����������� �����,NaN,37.390365,"�������� � 05:30:00, �������� � 01:00:00, ����...","�������� � 05:30:00, �������� � 01:00:00, ����...","��������, ����-����� 2, ��������� 2",��������,[],"{'type': 'Point', 'coordinates': [37.390365, 5...",886135571
1028,4.0,4.0,1066,55.648399,����������� �����,NaN,37.371789,"�������� � 05:25:00, �������� � 01:00:00, ����...","�������� � 05:25:00, �������� � 01:00:00, ����...","��������� �����, ����-����� 2, ��������� 1",��������� �����,[],"{'type': 'Point', 'coordinates': [37.371789, 5...",886135588
1029,4.0,4.0,1067,55.647142,����������� �����,NaN,37.368589,"�������� � 05:25:00, �������� � 01:00:00, ����...","�������� � 05:25:00, �������� � 01:00:00, ����...","��������� �����, ����-����� 1, ��������� 2",��������� �����,[],"{'type': 'Point', 'coordinates': [37.368589, 5...",886135614
1030,4.0,4.0,1068,55.640613,����������� �����,NaN,37.356337,"�������� � 05:25:00, �������� � 01:00:00, ����...","�������� � 05:25:00, �������� � 01:00:00, ����...","���������������, ����-����� 3, ��������� 1",���������������,[],"{'type': 'Point', 'coordinates': [37.356337, 5...",886135618
1031,4.0,4.0,1069,55.640068,����������� �����,NaN,37.356265,"�������� � 05:25:00, �������� � 01:00:00, ����...","�������� � 05:25:00, �������� � 01:00:00, ����...","���������������, ����-����� 4, ��������� 1",���������������,[],"{'type': 'Point', 'coordinates': [37.356265, 5...",886135644
1032,4.0,4.0,1070,55.638905,����������� �����,NaN,37.353450,"�������� � 05:25:00, �������� � 01:00:00, ����...","�������� � 05:25:00, �������� � 01:00:00, ����...","���������������, ����-����� 1, ��������� 2",���������������,[],"{'type': 'Point', 'coordinates': [37.35345, 55...",886135664
1033,4.0,4.0,1071,55.638629,����������� �����,NaN,37.353960,"�������� � 05:25:00, �������� � 01:00:00, ����...","�������� � 05:25:00, �������� � 01:00:00, ����...","���������������, ����-����� 2, ��������� 2",���������������,[],"{'type': 'Point', 'coordinates': [37.35396, 55...",886135675
1034,3.0,3.0,1072,55.634202,����������� �����,NaN,37.334769,"�������� � 05:30:00, �������� � 01:00:00, ����...","�������� � 05:30:00, �������� � 01:00:00, ����...","�����������, ����-����� 3, ��������� 1",�����������,[],"{'type': 'Point', 'coordinates': [37.334769, 5...",886135690
1035,3.0,3.0,1073,55.634309,����������� �����,NaN,37.335603,"�������� � 05:30:00, �������� � 01:00:00, ����...","�������� � 05:30:00, �������� � 01:00:00, ����...","�����������, ����-����� 4, ��������� 1",�����������,[],"{'type': 'Point', 'coordinates': [37.335603, 5...",886135701
1036,3.0,3.0,1074,55.634466,����������� �����,NaN,37.336590,"�������� � 05:30:00, �������� � 01:00:00, ����...","�������� � 05:30:00, �������� � 01:00:00, ����...","�����������, ����-����� 5, ��������� 1",�����������,[],"{'type': 'Point', 'coordinates': [37.33659, 55...",886135715
1037,3.0,3.0,1075,55.633872,����������� �����,NaN,37.332704,"�������� � 05:30:00, �������� � 01:00:00, ����...","�������� � 05:30:00, �������� � 01:00:00, ����...","�����������, ����-����� 1, ��������� 2",�����������,[],"{'type': 'Point', 'coordinates': [37.332704, 5...",886135751
1038,3.0,3.0,1076,55.633998,����������� �����,NaN,37.333584,"�������� � 05:30:00, �������� � 01:00:00, ����...","�������� � 05:30:00, �������� � 01:00:00, ����...","�����������, ����-����� 2, ��������� 2",�����������,[],"{'type': 'Point', 'coordinates': [37.333584, 5...",886135788

In [3]:
df['geoData']

0       {'type': 'Point', 'coordinates': [37.6309849, ...
1       {'type': 'Point', 'coordinates': [37.6316766, ...
2       {'type': 'Point', 'coordinates': [37.6312698, ...
3       {'type': 'Point', 'coordinates': [37.6319506, ...
4       {'type': 'Point', 'coordinates': [37.6331045, ...
5       {'type': 'Point', 'coordinates': [37.6336406, ...
6       {'type': 'Point', 'coordinates': [37.6341765, ...
7       {'type': 'Point', 'coordinates': [37.6349733, ...
8       {'type': 'Point', 'coordinates': [37.6296491, ...
9       {'type': 'Point', 'coordinates': [37.5392381, ...
10      {'type': 'Point', 'coordinates': [37.7526435, ...
11      {'type': 'Point', 'coordinates': [37.7517426, ...
12      {'type': 'Point', 'coordinates': [37.5416454, ...
13      {'type': 'Point', 'coordinates': [37.5764394, ...
14      {'type': 'Point', 'coordinates': [37.5771475, ...
15      {'type': 'Point', 'coordinates': [37.5149399, ...
16      {'type': 'Point', 'coordinates': [37.61792, 55...
17      {'type': 'Point', 'coordinates': [37.6207903, ...
18      {'type': 'Point', 'coordinates': [37.5402196, ...
19      {'type': 'Point', 'coordinates': [37.5409869, ...
20      {'type': 'Point', 'coordinates': [37.6571455, ...
21      {'type': 'Point', 'coordinates': [37.6576959, ...
22      {'type': 'Point', 'coordinates': [37.6553567, ...
23      {'type': 'Point', 'coordinates': [37.5964667, ...
24      {'type': 'Point', 'coordinates': [37.5418665, ...
25      {'type': 'Point', 'coordinates': [37.656097, 5...
26      {'type': 'Point', 'coordinates': [37.7521499, ...
27      {'type': 'Point', 'coordinates': [37.54459, 55...
28      {'type': 'Point', 'coordinates': [37.5446657, ...
29      {'type': 'Point', 'coordinates': [37.5488844, ...
                              ...
1009    {'type': 'Point', 'coordinates': [37.546029, 5...
1010    {'type': 'Point', 'coordinates': [37.545471, 5...
1011    {'type': 'Point', 'coordinates': [37.547928, 5...
1012    {'type': 'Point', 'coordinates': [37.547848, 5...
1013    {'type': 'Point', 'coordinates': [37.546311, 5...
1014    {'type': 'Point', 'coordinates': [37.546223, 5...
1015    {'type': 'Point', 'coordinates': [37.483401, 5...
1016    {'type': 'Point', 'coordinates': [37.483989, 5...
1017    {'type': 'Point', 'coordinates': [37.450153, 5...
1018    {'type': 'Point', 'coordinates': [37.450714, 5...
1019    {'type': 'Point', 'coordinates': [37.451291, 5...
1020    {'type': 'Point', 'coordinates': [37.447595, 5...
1021    {'type': 'Point', 'coordinates': [37.418369, 5...
1022    {'type': 'Point', 'coordinates': [37.418985, 5...
1023    {'type': 'Point', 'coordinates': [37.415586, 5...
1024    {'type': 'Point', 'coordinates': [37.416347, 5...
1025    {'type': 'Point', 'coordinates': [37.391905, 5...
1026    {'type': 'Point', 'coordinates': [37.389874, 5...
1027    {'type': 'Point', 'coordinates': [37.390365, 5...
1028    {'type': 'Point', 'coordinates': [37.371789, 5...
1029    {'type': 'Point', 'coordinates': [37.368589, 5...
1030    {'type': 'Point', 'coordinates': [37.356337, 5...
1031    {'type': 'Point', 'coordinates': [37.356265, 5...
1032    {'type': 'Point', 'coordinates': [37.35345, 55...
1033    {'type': 'Point', 'coordinates': [37.35396, 55...
1034    {'type': 'Point', 'coordinates': [37.334769, 5...
1035    {'type': 'Point', 'coordinates': [37.335603, 5...
1036    {'type': 'Point', 'coordinates': [37.33659, 55...
1037    {'type': 'Point', 'coordinates': [37.332704, 5...
1038    {'type': 'Point', 'coordinates': [37.333584, 5...
Name: geoData, Length: 1039, dtype: object

In [4]:
a = np.array(df['geoData'].values)

In [5]:
a

array([{'type': 'Point', 'coordinates': [37.6309849, 55.7567672]},
       {'type': 'Point', 'coordinates': [37.6316766, 55.7573154]},
       {'type': 'Point', 'coordinates': [37.6312698, 55.7568819]}, ...,
       {'type': 'Point', 'coordinates': [37.33659, 55.634466]},
       {'type': 'Point', 'coordinates': [37.332704, 55.633872]},
       {'type': 'Point', 'coordinates': [37.333584, 55.633998]}],
      dtype=object)

In [6]:
res = []
for dic in a:
#     print(dic['coordinates'])
    res.append({'type' : 'underground', 'lat' : dic['coordinates'][1], 'lon': dic['coordinates'][0]})
res

[{'type': 'underground', 'lat': 55.7567672, 'lon': 37.6309849},
 {'type': 'underground', 'lat': 55.7573154, 'lon': 37.6316766},
 {'type': 'underground', 'lat': 55.7568819, 'lon': 37.6312698},
 {'type': 'underground', 'lat': 55.7572362, 'lon': 37.6319506},
 {'type': 'underground', 'lat': 55.7531976, 'lon': 37.6331045},
 {'type': 'underground', 'lat': 55.7531116, 'lon': 37.6336406},
 {'type': 'underground', 'lat': 55.7541345, 'lon': 37.6341765},
 {'type': 'underground', 'lat': 55.7540238, 'lon': 37.6349733},
 {'type': 'underground', 'lat': 55.756604, 'lon': 37.6296491},
 {'type': 'underground', 'lat': 55.6553856, 'lon': 37.5392381},
 {'type': 'underground', 'lat': 55.660114, 'lon': 37.7526435},
 {'type': 'underground', 'lat': 55.6600507, 'lon': 37.7517426},
 {'type': 'underground', 'lat': 55.5450107, 'lon': 37.5416454},
 {'type': 'underground', 'lat': 55.5702548, 'lon': 37.5764394},
 {'type': 'underground', 'lat': 55.5700929, 'lon': 37.5771475},
 {'type': 'underground', 'lat': 55.5376805, 'lon': 37.5149399},
 {'type': 'underground', 'lat': 55.653075, 'lon': 37.61792},
 {'type': 'underground', 'lat': 55.6532132, 'lon': 37.6207903},
 {'type': 'underground', 'lat': 55.6563232, 'lon': 37.5402196},
 {'type': 'underground', 'lat': 55.6581538, 'lon': 37.5409869},
 {'type': 'underground', 'lat': 55.6346647, 'lon': 37.6571455},
 {'type': 'underground', 'lat': 55.6350525, 'lon': 37.6576959},
 {'type': 'underground', 'lat': 55.6367212, 'lon': 37.6553567},
 {'type': 'underground', 'lat': 55.6528887, 'lon': 37.5964667},
 {'type': 'underground', 'lat': 55.6578591, 'lon': 37.5418665},
 {'type': 'underground', 'lat': 55.636917, 'lon': 37.656097},
 {'type': 'underground', 'lat': 55.6599107, 'lon': 37.7521499},
 {'type': 'underground', 'lat': 55.7733859, 'lon': 37.54459},
 {'type': 'underground', 'lat': 55.774, 'lon': 37.5446657},
 {'type': 'underground', 'lat': 55.7732229, 'lon': 37.5488844},
 {'type': 'underground', 'lat': 55.774375, 'lon': 37.549137},
 {'type': 'underground', 'lat': 55.7753945, 'lon': 37.5826448},
 {'type': 'underground', 'lat': 55.7772182, 'lon': 37.5820187},
 {'type': 'underground', 'lat': 55.777448, 'lon': 37.585696},
 {'type': 'underground', 'lat': 55.6418619, 'lon': 37.5253262},
 {'type': 'underground', 'lat': 55.6415467, 'lon': 37.5258676},
 {'type': 'underground', 'lat': 55.643845999999996, 'lon': 37.5267264},
 {'type': 'underground', 'lat': 55.6544846, 'lon': 37.6478561},
 {'type': 'underground', 'lat': 55.655628, 'lon': 37.649519},
 {'type': 'underground', 'lat': 55.742922, 'lon': 37.564427},
 {'type': 'underground', 'lat': 55.743152, 'lon': 37.565065},
 {'type': 'underground', 'lat': 55.743792, 'lon': 37.567119},
 {'type': 'underground', 'lat': 55.743743, 'lon': 37.56757},
 {'type': 'underground', 'lat': 55.7562297, 'lon': 37.6301157},
 {'type': 'underground', 'lat': 55.7569941, 'lon': 37.6306312},
 {'type': 'underground', 'lat': 55.655689699999996, 'lon': 37.5384065},
 {'type': 'underground', 'lat': 55.6565991, 'lon': 37.5393716},
 {'type': 'underground', 'lat': 55.6530037, 'lon': 37.5969816},
 {'type': 'underground', 'lat': 55.6524548, 'lon': 37.5967073},
 {'type': 'underground', 'lat': 55.6525546, 'lon': 37.597159},
 {'type': 'underground', 'lat': 55.6534068, 'lon': 37.5997069},
 {'type': 'underground', 'lat': 55.6529558, 'lon': 37.5998679},
 {'type': 'underground', 'lat': 55.653416, 'lon': 37.6001946},
 {'type': 'underground', 'lat': 55.6529588, 'lon': 37.6003877},
 {'type': 'underground', 'lat': 55.839091, 'lon': 37.487262},
 {'type': 'underground', 'lat': 55.8198862, 'lon': 37.4966084},
 {'type': 'underground', 'lat': 55.8200536, 'lon': 37.4978475},
 {'type': 'underground', 'lat': 55.8483448, 'lon': 37.5903673},
 {'type': 'underground', 'lat': 55.8405471, 'lon': 37.4861169},
 {'type': 'underground', 'lat': 55.8180816, 'lon': 37.4980328},
 {'type': 'underground', 'lat': 55.8183579, 'lon': 37.4990514},
 {'type': 'underground', 'lat': 55.8178071, 'lon': 37.4995989},
 {'type': 'underground', 'lat': 55.7256857, 'lon': 37.685034},
 {'type': 'underground', 'lat': 55.6907047, 'lon': 37.7564272},
 {'type': 'underground', 'lat': 55.836391, 'lon': 37.381439},
 {'type': 'underground', 'lat': 55.834667, 'lon': 37.383293},
 {'type': 'underground', 'lat': 55.7090889, 'lon': 37.5579244},
 {'type': 'underground', 'lat': 55.7117344, 'lon': 37.5616417},
 {'type': 'underground', 'lat': 55.7119958, 'lon': 37.5611434},
 {'type': 'underground', 'lat': 55.7091802, 'lon': 37.5573612},
 {'type': 'underground', 'lat': 55.7483761, 'lon': 37.5440139},
 {'type': 'underground', 'lat': 55.750243, 'lon': 37.542609},
 {'type': 'underground', 'lat': 55.7158154, 'lon': 37.8191351},
 {'type': 'underground', 'lat': 55.7157276, 'lon': 37.8176759},
 {'type': 'underground', 'lat': 55.8242068, 'lon': 37.6386606},
 {'type': 'underground', 'lat': 55.790523, 'lon': 37.556447},
 {'type': 'underground', 'lat': 55.7889852, 'lon': 37.559939},
 {'type': 'underground', 'lat': 55.807873, 'lon': 37.580249},
 {'type': 'underground', 'lat': 55.8080919, 'lon': 37.5814213},
 {'type': 'underground', 'lat': 55.7290528, 'lon': 37.6227295},
 {'type': 'underground', 'lat': 55.610926, 'lon': 37.716543},
 {'type': 'underground', 'lat': 55.6434915, 'lon': 37.5272194},
 {'type': 'underground', 'lat': 55.884046, 'lon': 37.6046466},
 {'type': 'underground', 'lat': 55.884215, 'lon': 37.601567},
 {'type': 'underground', 'lat': 55.88357, 'lon': 37.605269},
 {'type': 'underground', 'lat': 55.7522884, 'lon': 37.6086853},
 {'type': 'underground', 'lat': 55.6323743, 'lon': 37.7434206},
 {'type': 'underground', 'lat': 55.6340555, 'lon': 37.7445891},
 {'type': 'underground', 'lat': 55.8459341, 'lon': 37.638487},
 {'type': 'underground', 'lat': 55.6535532, 'lon': 37.6179177},
 {'type': 'underground', 'lat': 55.6536989, 'lon': 37.6230912},
 {'type': 'underground', 'lat': 55.8224642, 'lon': 37.6413856},
 {'type': 'underground', 'lat': 55.8196763, 'lon': 37.6407422},
 {'type': 'underground', 'lat': 55.8200023, 'lon': 37.6396426},
 {'type': 'underground', 'lat': 55.8200023, 'lon': 37.6396426},
 {'type': 'underground', 'lat': 55.8466671, 'lon': 37.6389383},
 {'type': 'underground', 'lat': 55.8439021, 'lon': 37.6373929},
 {'type': 'underground', 'lat': 55.82028, 'lon': 37.639943},
 {'type': 'underground', 'lat': 55.8460848, 'lon': 37.5892624},
 {'type': 'underground', 'lat': 55.724604, 'lon': 37.687808},
 {'type': 'underground', 'lat': 55.6911954, 'lon': 37.7511401},
 {'type': 'underground', 'lat': 55.6911954, 'lon': 37.7511401},
 {'type': 'underground', 'lat': 55.610256, 'lon': 37.71815},
 {'type': 'underground', 'lat': 55.819972, 'lon': 37.641058},
 {'type': 'underground', 'lat': 55.6910781, 'lon': 37.7515886},
 {'type': 'underground', 'lat': 55.690745, 'lon': 37.7552393},
 {'type': 'underground', 'lat': 55.610249, 'lon': 37.716893999999996},
 {'type': 'underground', 'lat': 55.6099729, 'lon': 37.7175836},
 {'type': 'underground', 'lat': 55.610893, 'lon': 37.720888},
 {'type': 'underground', 'lat': 55.807779, 'lon': 37.580614},
 {'type': 'underground', 'lat': 55.8081488, 'lon': 37.5818692},
 {'type': 'underground', 'lat': 55.7178288, 'lon': 37.6762283},
 {'type': 'underground', 'lat': 55.6134881, 'lon': 37.745559},
 {'type': 'underground', 'lat': 55.6133905, 'lon': 37.744236},
 {'type': 'underground', 'lat': 55.7877899, 'lon': 37.7798923},
 {'type': 'underground', 'lat': 55.7878638, 'lon': 37.7833622},
 {'type': 'underground', 'lat': 55.6343754, 'lon': 37.5189922},
 {'type': 'underground', 'lat': 55.632188, 'lon': 37.519367},
 {'type': 'underground', 'lat': 55.6346877, 'lon': 37.5197964},
 {'type': 'underground', 'lat': 55.6340114, 'lon': 37.5199465},
 {'type': 'underground', 'lat': 55.6339138, 'lon': 37.5205105},
 {'type': 'underground', 'lat': 55.6142123, 'lon': 37.746215},
 {'type': 'underground', 'lat': 55.6136532, 'lon': 37.7462738},
 {'type': 'underground', 'lat': 55.6136652, 'lon': 37.7466762},
 {'type': 'underground', 'lat': 55.6142302, 'lon': 37.7465907},
 {'type': 'underground', 'lat': 55.6134561, 'lon': 37.7424333},
 {'type': 'underground', 'lat': 55.6138351, 'lon': 37.6935179},
 {'type': 'underground', 'lat': 55.6141812, 'lon': 37.6940766},
 {'type': 'underground', 'lat': 55.862542, 'lon': 37.604393},
 {'type': 'underground', 'lat': 55.864331, 'lon': 37.605332},
 {'type': 'underground', 'lat': 55.864174, 'lon': 37.606024},
 {'type': 'underground', 'lat': 55.8627468, 'lon': 37.6038026},
 {'type': 'underground', 'lat': 55.7569836, 'lon': 37.6145304},
 {'type': 'underground', 'lat': 55.7567501, 'lon': 37.6146643},
 {'type': 'underground', 'lat': 55.6140271, 'lon': 37.7428056},
 {'type': 'underground', 'lat': 55.6134786, 'lon': 37.7429054},
 {'type': 'underground', 'lat': 55.6140076, 'lon': 37.7423932},
 {'type': 'underground', 'lat': 55.7602928, 'lon': 37.5769378},
 {'type': 'underground', 'lat': 55.7799823, 'lon': 37.6660804},
 {'type': 'underground', 'lat': 55.768377, 'lon': 37.648027},
 {'type': 'underground', 'lat': 55.7697611, 'lon': 37.6503572},
 {'type': 'underground', 'lat': 55.7323251, 'lon': 37.6655383},
 {'type': 'underground', 'lat': 55.7456522, 'lon': 37.6053316},
 {'type': 'underground', 'lat': 55.7456522, 'lon': 37.6053316},
 {'type': 'underground', 'lat': 55.7449791, 'lon': 37.6015583},
 {'type': 'underground', 'lat': 55.757872, 'lon': 37.407313},
 {'type': 'underground', 'lat': 55.755564, 'lon': 37.407657},
 {'type': 'underground', 'lat': 55.755375, 'lon': 37.408601},
 {'type': 'underground', 'lat': 55.757724, 'lon': 37.408585},
 {'type': 'underground', 'lat': 55.757423, 'lon': 37.40738},
 {'type': 'underground', 'lat': 55.758057, 'lon': 37.408542},
 {'type': 'underground', 'lat': 55.755663, 'lon': 37.408899},
 {'type': 'underground', 'lat': 55.755342, 'lon': 37.407686},
 {'type': 'underground', 'lat': 55.671235, 'lon': 37.555321},
 {'type': 'underground', 'lat': 55.729349, 'lon': 37.611311},
 {'type': 'underground', 'lat': 55.7313189, 'lon': 37.6126133},
 {'type': 'underground', 'lat': 55.7939801, 'lon': 37.4922446},
 {'type': 'underground', 'lat': 55.7941438, 'lon': 37.4919278},
 {'type': 'underground', 'lat': 55.7941853, 'lon': 37.4925294},
 {'type': 'underground', 'lat': 55.7943253, 'lon': 37.4922657},
 {'type': 'underground', 'lat': 55.671056, 'lon': 37.55586},
 {'type': 'underground', 'lat': 55.7928291, 'lon': 37.4944062},
 {'type': 'underground', 'lat': 55.753755, 'lon': 37.635443},
 {'type': 'underground', 'lat': 55.7062422, 'lon': 37.6853525},
 {'type': 'underground', 'lat': 55.7064123, 'lon': 37.685589},
 {'type': 'underground', 'lat': 55.676834, 'lon': 37.6627956},
 {'type': 'underground', 'lat': 55.6776867, 'lon': 37.6630158},
 {'type': 'underground', 'lat': 55.679302, 'lon': 37.6634124},
 {'type': 'underground', 'lat': 55.676747, 'lon': 37.6643994},
 {'type': 'underground', 'lat': 55.6776258, 'lon': 37.6645394},
 {'type': 'underground', 'lat': 55.679487, 'lon': 37.664952},
 {'type': 'underground', 'lat': 55.679214, 'lon': 37.664904},
 {'type': 'underground', 'lat': 55.6795598, 'lon': 37.6634398},
 {'type': 'underground', 'lat': 55.775717, 'lon': 37.655289},
 {'type': 'underground', 'lat': 55.7753031, 'lon': 37.6558575},
 {'type': 'underground', 'lat': 55.7749342, 'lon': 37.6563189},
 {'type': 'underground', 'lat': 55.77673, 'lon': 37.655917},
 {'type': 'underground', 'lat': 55.7755021, 'lon': 37.656078},
 {'type': 'underground', 'lat': 55.775835, 'lon': 37.655895},
 {'type': 'underground', 'lat': 55.6325183, 'lon': 37.5180365},
 {'type': 'underground', 'lat': 55.779503, 'lon': 37.601021},
 {'type': 'underground', 'lat': 55.601509, 'lon': 37.552851},
 {'type': 'underground', 'lat': 55.6019926, 'lon': 37.5528887},
 {'type': 'underground', 'lat': 55.6696118, 'lon': 37.5536016},
 {'type': 'underground', 'lat': 55.6694298, 'lon': 37.5541228},
 {'type': 'underground', 'lat': 55.7927107, 'lon': 37.494672},
 {'type': 'underground', 'lat': 55.7930327, 'lon': 37.494715},
 {'type': 'underground', 'lat': 55.7929182, 'lon': 37.4949407},
 {'type': 'underground', 'lat': 55.612207, 'lon': 37.695852},
 {'type': 'underground', 'lat': 55.7084099, 'lon': 37.5874891},
 {'type': 'underground', 'lat': 55.7590119, 'lon': 37.6261416},
 {'type': 'underground', 'lat': 55.7588185, 'lon': 37.6264345},
 {'type': 'underground', 'lat': 55.7589691, 'lon': 37.6271876},
 {'type': 'underground', 'lat': 55.759298, 'lon': 37.6281027},
 {'type': 'underground', 'lat': 55.7600076, 'lon': 37.6280056},
 {'type': 'underground', 'lat': 55.7596192, 'lon': 37.6284663},
 {'type': 'underground', 'lat': 55.759958, 'lon': 37.628384},
 {'type': 'underground', 'lat': 55.7590701, 'lon': 37.6257502},
 {'type': 'underground', 'lat': 55.674484, 'lon': 37.7610191},
 {'type': 'underground', 'lat': 55.6767171, 'lon': 37.7618126},
 {'type': 'underground', 'lat': 55.7593986, 'lon': 37.6283278},
 {'type': 'underground', 'lat': 55.6770532, 'lon': 37.7618992},
 {'type': 'underground', 'lat': 55.6771029, 'lon': 37.7621184},
 {'type': 'underground', 'lat': 55.677062, 'lon': 37.7627843},
 {'type': 'underground', 'lat': 55.6769211, 'lon': 37.7629313},
 {'type': 'underground', 'lat': 55.7406722, 'lon': 37.656423},
 {'type': 'underground', 'lat': 55.7411071, 'lon': 37.6567019},
 {'type': 'underground', 'lat': 55.7935291, 'lon': 37.6168452},
 {'type': 'underground', 'lat': 55.7935652, 'lon': 37.615922499999996},
 {'type': 'underground', 'lat': 55.7971408, 'lon': 37.6169578},
 {'type': 'underground', 'lat': 55.651296, 'lon': 37.743716},
 {'type': 'underground', 'lat': 55.6510084, 'lon': 37.7438447},
 {'type': 'underground', 'lat': 55.6491637, 'lon': 37.7438608},
 {'type': 'underground', 'lat': 55.6489065, 'lon': 37.7439623},
 {'type': 'underground', 'lat': 55.649279, 'lon': 37.744483},
 {'type': 'underground', 'lat': 55.648937, 'lon': 37.744606},
 {'type': 'underground', 'lat': 55.7616171, 'lon': 37.6241745},
 {'type': 'underground', 'lat': 55.705308, 'lon': 37.763751},
 {'type': 'underground', 'lat': 55.7060321, 'lon': 37.7640246},
 {'type': 'underground', 'lat': 55.704826, 'lon': 37.767415},
 {'type': 'underground', 'lat': 55.705532, 'lon': 37.767726},
 {'type': 'underground', 'lat': 55.730675, 'lon': 37.445477},
 {'type': 'underground', 'lat': 55.73082, 'lon': 37.446469},
 {'type': 'underground', 'lat': 55.730541, 'lon': 37.445568},
 {'type': 'underground', 'lat': 55.730666, 'lon': 37.446528},
 {'type': 'underground', 'lat': 55.758613, 'lon': 37.658992},
 {'type': 'underground', 'lat': 55.7585107, 'lon': 37.6601558},
 {'type': 'underground', 'lat': 55.757855, 'lon': 37.660164},
 {'type': 'underground', 'lat': 55.7561757, 'lon': 37.6599122},
 {'type': 'underground', 'lat': 55.7394196, 'lon': 37.5347739},
 {'type': 'underground', 'lat': 55.7405718, 'lon': 37.534101},
 {'type': 'underground', 'lat': 55.7068188, 'lon': 37.5850864},
 {'type': 'underground', 'lat': 55.651236, 'lon': 37.743045},
 {'type': 'underground', 'lat': 55.6509113, 'lon': 37.7431633},
 {'type': 'underground', 'lat': 55.771143, 'lon': 37.594548},
 {'type': 'underground', 'lat': 55.76926, 'lon': 37.596533},
 {'type': 'underground', 'lat': 55.6728519, 'lon': 37.6110945},
 {'type': 'underground', 'lat': 55.663502, 'lon': 37.6062028},
 {'type': 'underground', 'lat': 55.6635432, 'lon': 37.6069995},
 {'type': 'underground', 'lat': 55.661613, 'lon': 37.6041081},
 {'type': 'underground', 'lat': 55.661751699999996, 'lon': 37.6047437},
 {'type': 'underground', 'lat': 55.6637839, 'lon': 37.6061591},
 {'type': 'underground', 'lat': 55.7522622, 'lon': 37.8145804},
 {'type': 'underground', 'lat': 55.751722, 'lon': 37.81491},
 {'type': 'underground', 'lat': 55.7512382, 'lon': 37.8185824},
 {'type': 'underground', 'lat': 55.7516932, 'lon': 37.8184026},
 {'type': 'underground', 'lat': 55.7461213, 'lon': 37.8655979},
 {'type': 'underground', 'lat': 55.744476, 'lon': 37.8658385},
 {'type': 'underground', 'lat': 55.7438943, 'lon': 37.8625401},
 {'type': 'underground', 'lat': 55.7441695, 'lon': 37.8623576},
 {'type': 'underground', 'lat': 55.745471, 'lon': 37.861671},
 {'type': 'underground', 'lat': 55.7422968, 'lon': 37.6292367},
 {'type': 'underground', 'lat': 55.7656698, 'lon': 37.604118},
 {'type': 'underground', 'lat': 55.8546831, 'lon': 37.354253},
 {'type': 'underground', 'lat': 55.855143, 'lon': 37.354014},
 {'type': 'underground', 'lat': 55.855288, 'lon': 37.353016},
 {'type': 'underground', 'lat': 55.857297, 'lon': 37.355414},
 {'type': 'underground', 'lat': 55.8557359, 'lon': 37.4755931},
 {'type': 'underground', 'lat': 55.8217898, 'lon': 37.609212},
 {'type': 'underground', 'lat': 55.619857, 'lon': 37.505166},
 {'type': 'underground', 'lat': 55.6198202, 'lon': 37.5063141},
 {'type': 'underground', 'lat': 55.886008, 'lon': 37.661087},
 {'type': 'underground', 'lat': 55.845533, 'lon': 37.363824},
 {'type': 'underground', 'lat': 55.846763, 'lon': 37.361271},
 {'type': 'underground', 'lat': 55.845982, 'lon': 37.360512},
 {'type': 'underground', 'lat': 55.74122, 'lon': 37.415713},
 {'type': 'underground', 'lat': 55.740201, 'lon': 37.417866},
 {'type': 'underground', 'lat': 55.82354, 'lon': 37.385197},
 {'type': 'underground', 'lat': 55.6822357, 'lon': 37.6209364},
 {'type': 'underground', 'lat': 55.682157, 'lon': 37.6216372},
 {'type': 'underground', 'lat': 55.7572616, 'lon': 37.614986},
 {'type': 'underground', 'lat': 55.7572071, 'lon': 37.6154233},
 {'type': 'underground', 'lat': 55.7566567, 'lon': 37.6156184},
 {'type': 'underground', 'lat': 55.7560971, 'lon': 37.6177488},
 {'type': 'underground', 'lat': 55.7568832, 'lon': 37.6155387},
 {'type': 'underground', 'lat': 55.7313438, 'lon': 37.6362414},
 {'type': 'underground', 'lat': 55.68216, 'lon': 37.6213636},
 {'type': 'underground', 'lat': 55.68417, 'lon': 37.6227098},
 {'type': 'underground', 'lat': 55.6729139, 'lon': 37.6103001},
 {'type': 'underground', 'lat': 55.7296879, 'lon': 37.6388141},
 {'type': 'underground', 'lat': 55.7350914, 'lon': 37.5933065},
 {'type': 'underground', 'lat': 55.7360872, 'lon': 37.5949799},
 {'type': 'underground', 'lat': 55.73644, 'lon': 37.51592},
 {'type': 'underground', 'lat': 55.735804, 'lon': 37.517105},
 {'type': 'underground', 'lat': 55.73631, 'lon': 37.517599},
 {'type': 'underground', 'lat': 55.735922, 'lon': 37.517692},
 {'type': 'underground', 'lat': 55.736633, 'lon': 37.517273},
 {'type': 'underground', 'lat': 55.7884901, 'lon': 37.7496596},
 {'type': 'underground', 'lat': 55.8879931, 'lon': 37.6614571},
 {'type': 'underground', 'lat': 55.7478886, 'lon': 37.533285},
 {'type': 'underground', 'lat': 55.7814401, 'lon': 37.5987019},
 {'type': 'underground', 'lat': 55.7819132, 'lon': 37.5991088},
 {'type': 'underground', 'lat': 55.7816926, 'lon': 37.5984772},
 {'type': 'underground', 'lat': 55.846255, 'lon': 37.359469},
 {'type': 'underground', 'lat': 55.846321, 'lon': 37.361159},
 {'type': 'underground', 'lat': 55.844829, 'lon': 37.363396},
 {'type': 'underground', 'lat': 55.847006, 'lon': 37.360486},
 {'type': 'underground', 'lat': 55.6115949, 'lon': 37.6032311},
 {'type': 'underground', 'lat': 55.795534, 'lon': 37.714863199999996},
 {'type': 'underground', 'lat': 55.7953081, 'lon': 37.7148765},
 {'type': 'underground', 'lat': 55.796922, 'lon': 37.716974},
 {'type': 'underground', 'lat': 55.795982, 'lon': 37.717060000000004},
 {'type': 'underground', 'lat': 55.7968666, 'lon': 37.7166493},
 {'type': 'underground', 'lat': 55.796064, 'lon': 37.717543},
 {'type': 'underground', 'lat': 55.7317821, 'lon': 37.664368},
 {'type': 'underground', 'lat': 55.7312101, 'lon': 37.6645773},
 {'type': 'underground', 'lat': 55.73131, 'lon': 37.664926},
 {'type': 'underground', 'lat': 55.6778375, 'lon': 37.5071875},
 {'type': 'underground', 'lat': 55.7819543, 'lon': 37.633349},
 {'type': 'underground', 'lat': 55.7795686, 'lon': 37.6335334},
 {'type': 'underground', 'lat': 55.6772799, 'lon': 37.5618179},
 {'type': 'underground', 'lat': 55.6770979, 'lon': 37.5623706},
 {'type': 'underground', 'lat': 55.6788868, 'lon': 37.5635613},
 {'type': 'underground', 'lat': 55.6786988, 'lon': 37.5640979},
 {'type': 'underground', 'lat': 55.7654151, 'lon': 37.6038161},

In [7]:
file = open("result/underground.json", "w")

file.write(json.dumps(res))

64676